### ISSUE TITLE
Implement Responsive Grid System in grid-plate / layouts

### ISSUE THREAD

**Issue by rickhumphries** [LRNWebComponents/hax-body#167]
Currently I can see a way of adding layouts to HAX which can create 50/50 columns etc. but I can't see a way to make these responsive (i.e. stack when reaching a certain width on mobile).

It would be useful to implement a grid system so the content author can define how the content will appear on different devices.

**Comment by btopro** [comment]
these are set in motion for this, step 1 of the grid-plate tag was simply making it exist. @nikkimk 's tag it's built on top of has responsive breakpoint capabilities we just haven't wired it up yet. Renaming your issue to be more action oriented since we have this in the works just not implemented yet

**Comment by btopro** [comment]
modified comment to remove links since we have a tag for this :) thx for putting this in

**Comment by rickhumphries** [comment]
ah nice one!

**Comment by btopro** [comment]
https://github.com/LRNWebComponents/responsive-grid is the tag fyi

**Comment by btopro** [comment]
closing as we have one, it's more about needing to improve what we have (which we know) :)
