### ISSUE TITLE
Polymer 3 Compatibility

### ISSUE THREAD

**Issue by lastmjs** [LRNWebComponents/hax-body#2]
Excited to start possible integration with [Prendus Question Elements](https://github.com/Prendus/prendus-question-elements), but must wait for hax-body to support Polymer 2 for proper interop.

**Comment by btopro** [comment]
can you give it a go based on whats' there currently and let us know where it fails? much of the elements we use are 2.x; i'm trying to nail down what parts of 1.x we're hooked to that we need to upgrade and get off of (I know listeners block is used some places but we've started moving off it). We want this to work with anything, polymer x.x.x or otherwise.

**Comment by lastmjs** [comment]
Yes, hopefully I can get to it within the week

**Comment by btopro** [comment]
the workflow (internally) for us to upgrade our entire portfolio to Polymer 3 / ESM based workflows has been established via https://github.com/elmsln/wcfactory.

This is entirely an experimental port and not tested and doesn't work (we're working on the end to end publishing implications) but https://github.com/elmsln/lrnwebcomponents/tree/master/elements/hax-body has a ported copy that would work in ESM based workflows.

After some more testing of the automated methods and internal training then we'll be moving over to the mono-repo to work on HAX as a polymer 3 capable element set

**Comment by btopro** [comment]
Got it
