### ISSUE TITLE
Creating text area on pressing the return key

### ISSUE THREAD

**Issue by rickhumphries** [LRNWebComponents/hax-body#3]
Raising this as a discussion point really in terms of content writing flow. 
When typing out content within a text area, should a new paragraph tag (text area) be generated when pressing the return key, rather than a div within the paragraph tag? And if so, would potentially require support for a break tag within the text area config options.

**Comment by btopro** [comment]
oo that stuff gets very tricky because it's dictated by the browser. There's some unfortunate things I've learened through this process about contenteditable across browsers. For example, because we polyfill to make this all work, firefox and Edge don't have the bulleted list options due to incompatibility.

As for the br; try holding down command or shift when you hit return and see if that puts those in the code. I think if we wanted it to actually do a break or start a new paragraph that we'd have to have a button define it. Some browsers will take the "indent" and actually inject blockquote tags (just how they decided to implement that) so then there's really a diminishing return on investment to keep trying to normalize those little behaviors.


@rickhumphries I'd also be curious what you'd think an optimal HTML comments workflow. I've been thinking we could make a tag that hides HTML comments in them and provides a little comment icon so you can edit just that thing in place to help make things more collaborative in building.

**Comment by rickhumphries** [comment]
Ah that's a shame. Yeh shift+return puts in a break tag. A shortcut to enter a paragraph tag too would be most useful because I can just imagine how many content authors out there are going to do a 'double return' to create the paragraph space, but I hear what you're saying.

I'll break open another issue for the comments workflow

**Comment by heyMP** [comment]
Need to move the cursor to the active node:
https://stackoverflow.com/questions/6249095/how-to-set-caretcursor-position-in-contenteditable-element-div

**Comment by btopro** [comment]
needs to take text after the caret position, cut it, and then insert it into the other element.

As usual, content operations are more complex then the whole system :)

**Comment by btopro** [comment]
got the focus part working however it leaves a return in the previous element. it's like it goes "I'm adding a return. I added a return. Oh I noticed I added a return what do you want me to do? Add another line, got it. Focus the other line, cool."

**Comment by btopro** [comment]
#72 continuing there as this is now in there but needs clean up
