### ISSUE TITLE
seems like some magic relative imports "../" needed to run locally

### ISSUE THREAD

**Issue by jpray** [LRNWebComponents/hax-body#83]
Forgive me, I think I'm missing something fundamental in trying to get these various LRNWebComponents web component projects running locally.  The demo html files all contain references like this

```
    <script src="../webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="../iron-component-page/iron-component-page.html">
```

It appears that these assets exist under the "bower_components" folder.  Are you all using some sort of symlinks or something so that these paths resolve when running `polymer serve`?

Thanks!

**Comment by btopro** [comment]
nope they'll resolve correctly when from polymer serve. Polymer fixes the path differences on the fly when in local dev because when in a production environment all the elements would live at the same level.

`polymer serve --open` from inside the directory should work after cloning the repo and running `bower install`

**Comment by jpray** [comment]
Thanks.  I've been working with web components for quite some time but am a Polymer noob.  Much appreciated!

**Comment by btopro** [comment]
np catch me on twitter for things like this in the future if it's faster @btopro
