### ISSUE TITLE
Behavior consistency issue: Remove bulleted list

### ISSUE THREAD

**Issue by starryeyez024** [LRNWebComponents/hax-body#86]
On the [HAX demo page](https://lrnwebcomponents.github.io/hax-body/components/hax-body/demo/), there doesn't seem to be a way to remove bullets from a bulleted list, either individually or as a whole list. 

![removing bulleted list item](https://user-images.githubusercontent.com/456863/39223325-7a94ef92-480f-11e8-91bb-5c38201776c8.gif)

**Comment by btopro** [comment]
Thx for the report. I still have to dig into the html spec and see how bullets are supposed to work. The first list is a bullet ed list without a paragraph wrapper. Down in the document it's inside a p tag so we gotta trap for both slightly differently. Thx for the gif that's super useful

**Comment by btopro** [comment]
hmm.. so from digging into some stack overflow it would appear that the correct way to implement HTML for lists is as follows:
```
<p>things and stuff</p>
<ul>
  <li>list of things</li>
</ul>
<p>another p tag</p>
```
However, browsers will interpret correctly (cause everyone screws it up) a list inside of a paragraph. We should go for making things semantically accurate as per the spec so maybe what we need to do is make those buttons NOT apply the browser based method of doing this and instead use our split paragraph methodology but for the list itself. This way if we register the ul and ol tags w/ the hax-store (like we do for a, img, iframe and other primitives) then we can get a specific menu per each of them while removing these functions from the normal p menu. I'll experiment a bit w/ the clicking workflow for users in each scenario and see what it feels like. Users will expect to just click the list buttons (thanks word!) yet we can't do the generic browser defined operation (which isn't supported in Firefox anyway but that's another issue)

**Comment by btopro** [comment]
This should be cleared up based on the demo being cleaned up as well as text operations seeing a lot of love. republishing demo now

**Comment by starryeyez024** [comment]
Hey @btopro , I know this issue is closed but I'm still unable to remove list formatting on haxtheweb.org. http://www.giphy.com/gifs/QmGPZHzn2vxH6bkMvP Should I open an issue in https://github.com/LRNWebComponents/wysiwyg-hax instead?

**Comment by btopro** [comment]
hmm... 

If you make a new one it's fine. It has to do w/ the semantics of a `<p>` wrapping a `<ul>` vs a non-wrapped `<ul>`. From reading the spec it would appear that when you do things the "right way" [tm] that it doesn't actually work the way you'd expect (bleh).

Semantically HTML wants `<ul>` to not be wrapped in anything; however, doing that then the bulleted list buttons won't work. So... either we could detect a pure `ul` and then hide those buttons while showing them in the context of a `p` tag; or, we could not follow the standard (which appears to be what the rest of the web is doing unfortunately lol) so that we can get the expected behavior of enable / disable a bullet list.

I'll reopen and adjust the title slightly

**Comment by btopro** [comment]
shadow DOM will help with this and we'll be switching to it in #2

**Comment by btopro** [comment]
finally fixed this.. wow this was way too hard
